### ISSUE TITLE
HTTPS issue on the documentation

### ISSUE THREAD

**Issue by christophelec** [celery/celeryproject#28] opened 2019-04-24 09:00 UTC
# Checklist

- [X] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Description

Using the search engine on the documentation, I followed the first link : https://docs.celeryproject.org/en/latest/userguide/configuration.html?highlight=backend which results in an SSL_ERROR_BAD_CERT_DOMAIN.

It seems the SSL certificate is only valid for readthedocs.org, not celeryproject

To reproduce : search for anything, for example http://docs.celeryproject.org/en/latest/search.html?q=backend&check_keywords=yes&area=default and follow a link

# Suggestions

I'm not sure I'm well placed to offer recommandation, but either providing a correct certificate via let's encrypt, or disabling https altogether could fix the issue

**Comment by spheron1** [comment] 2019-05-28 21:11
Judging by https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-ssl, it looks like a change is required for the docs.celeryproject.org CNAME DNS record from "celery.readthedocs.org" to "readthedocs.io" so that the site is proxied via CloudFlare and they can issue an SSL certificate for the custom domain.

**Comment by hartwork** [comment] 2019-06-02 15:02
I would like to raise urgency here. The net is full of https links to celery doss (and rightfully so in my opinion) so it would be nice to get this fixed sooner than latter. Thanks!

**Comment by jerr0328** [comment] 2019-06-25 05:35
Looks like a duplicate of #24, should continue to push there.

**Closed** 2019-06-30 18:23 UTC
